/**
 * Public authoring surface for Hunk extensions, published as `hunkdiff/extension`.
 *
 * Extensions import types from here and default-export a factory:
 *
 * ```ts
 * import type { HunkExtensionAPI } from "hunkdiff/extension";
 *
 * export default function (hunk: HunkExtensionAPI) {
 *   hunk.registerFileLanguage(".prisma", "graphql");
 * }
 * ```
 *
 * Only façade types belong here. Everything exported is something Hunk intends
 * to keep stable for the declared `apiVersion`, and everything is declared in
 * `./types` — or, for the key-chord grammar, `./keys` — so the published
 * declarations stay free of Hunk internals.
 *
 * The relative specifiers below carry an explicit `.js` extension. TypeScript
 * maps them back to `./types.ts` when compiling this repo, and emission copies
 * them verbatim into the published declarations — where `moduleResolution:
 * "nodenext"` consumers *require* an explicit extension. Dropping it makes the
 * published `hunkdiff/extension` types fail to resolve for every ESM consumer.
 */
export { matchesKey, matchesKeyChord, parseKeyChord } from "./keys.js";
export type { ParsedKeyChord } from "./keys.js";
export {
  HUNK_CORE_VCS_DETECTION_PRIORITY,
  HUNK_DEFAULT_VCS_DETECTION_PRIORITY,
  HUNK_EXTENSION_API_VERSION,
  HUNK_VCS_DETECTION_BASELINE_PRIORITY,
  HUNK_EXTENSION_USER_ERROR_NAME,
  HunkExtensionUserError,
} from "./types.js";
export type {
  AgentAnnotation,
  AgentFileContext,
  ChangesetTransform,
  CustomSyntaxColorsConfig,
  CustomSyntaxScopesConfig,
  CustomThemeConfig,
  ExtensionChangeset,
  ExtensionContext,
  ExtensionDiffFile,
  ExtensionDiffHunk,
  ExtensionFileChangeRange,
  ExtensionFileLanguageMatcher,
  ExtensionFileSide,
  ExtensionFileView,
  ExtensionFileViewCodeDocument,
  ExtensionFileViewControls,
  ExtensionFileViewInput,
  ExtensionFileViewLayout,
  ExtensionFileViewMode,
  ExtensionFileViewModeContext,
  ExtensionFileViewModeKeyResult,
  ExtensionFileViewRow,
  ExtensionFileViewRowComponentProps,
  ExtensionFileViewSourceRange,
  ExtensionFileViewSpan,
  ExtensionFileViewSyntaxReference,
  ExtensionKeyEvent,
  ExtensionKeyboardMode,
  ExtensionKeyboardModeContext,
  ExtensionKeyboardModeControls,
  ExtensionKeyboardModeKeyResult,
  ExtensionLineHighlight,
  ExtensionLineHighlightControls,
  ExtensionLineHighlightInput,
  ExtensionLineHighlightTone,
  ExtensionLineHighlighter,
  ExtensionCustomEventHandler,
  ExtensionEventBus,
  ExtensionEventContext,
  ExtensionEventHandler,
  ExtensionEventName,
  ExtensionEventPayloads,
  ExtensionNoteChangeKind,
  ExtensionFactory,
  ExtensionCliCommand,
  ExtensionCliCommandContext,
  ExtensionCliCommandHandler,
  ExtensionCliCommandResult,
  ExtensionCliDelegateResult,
  ExtensionCliExitResult,
  ExtensionCliWriter,
  ExtensionReviewDescriptor,
  ExtensionReviewDescriptorBase,
  ExtensionChangeRequestReviewDescriptor,
  ExtensionCommitReviewDescriptor,
  ExtensionComparisonCommitDescriptor,
  ExtensionComparisonReviewDescriptor,
  ExtensionCommand,
  ExtensionCommandContext,
  ExtensionCommandControls,
  ExtensionCommandExecutionOptions,
  ExtensionCommandHandler,
  ExtensionReviewSelection,
  ExtensionReviewControls,
  ExtensionReviewReloadControls,
  ExtensionReviewReloadResult,
  ExtensionReviewSnapshot,
  ExtensionReviewSnapshotFile,
  ExtensionReviewSnapshotLineAddress,
  ExtensionReviewSnapshotNote,
  ExtensionReviewSnapshotNoteAnchor,
  ExtensionConfirmOptions,
  ExtensionDialogs,
  ExtensionInputOptions,
  ExtensionPromptControls,
  ExtensionPromptLineOptions,
  ExtensionStatusItem,
  ExtensionStatusLineControls,
  ExtensionStatusSpan,
  ExtensionSelectOptions,
  ExtensionSessionOptions,
  ExtensionNotifyType,
  ExtensionPaintTheme,
  ExtensionPane,
  ExtensionPaneActions,
  ExtensionPaneAvailabilityContext,
  ExtensionPaneComponent,
  ExtensionPaneControls,
  ExtensionPaneKeybindings,
  ExtensionPanePlacement,
  ExtensionPaneProps,
  ExtensionPaneTheme,
  ExtensionPaneSize,
  ExtensionHorizontalPane,
  ExtensionVerticalPane,
  ExtensionCurrentLinePaint,
  ExtensionCanonicalLayoutMode,
  ExtensionCanonicalResolvedLayout,
  ExtensionLayoutMode,
  ExtensionLegacyLayout,
  ExtensionResolvedLayout,
  ExtensionReviewNavigation,
  ExtensionReviewNote,
  ExtensionSidebarActions,
  ExtensionSidebarKeybindings,
  ExtensionSidebarComponent,
  ExtensionSidebarControls,
  ExtensionSidebarPlacement,
  ExtensionSidebarTheme,
  ExtensionSidebarView,
  ExtensionSidebarViewProps,
  ExtensionThemeConfig,
  ExtensionVcsAdapter,
  ExtensionVcsDetection,
  ExtensionVcsDiffInput,
  ExtensionVcsDiscardHunkRequest,
  ExtensionVcsDirectoryEntriesWatchTarget,
  ExtensionVcsDirectoryTreeWatchTarget,
  ExtensionVcsExtraFile,
  ExtensionVcsExtraPatchFile,
  ExtensionVcsFileChangeType,
  ExtensionVcsFileSide,
  ExtensionVcsFileSourceReader,
  ExtensionVcsFileSourceRequest,
  ExtensionVcsFileSourceResult,
  ExtensionVcsFileSourceTooLarge,
  ExtensionVcsFileStats,
  ExtensionVcsHistoryCapability,
  ExtensionVcsHistoryCommit,
  ExtensionVcsHistoryDecoration,
  ExtensionVcsHistoryInput,
  ExtensionVcsHistoryPage,
  ExtensionVcsHistoryRangeReviewAction,
  ExtensionVcsHistoryRangeSelection,
  ExtensionVcsHistoryReviewAction,
  ExtensionVcsHistoryReviewOptions,
  ExtensionVcsHistorySource,
  ExtensionVcsLoadContext,
  ExtensionVcsOperation,
  ExtensionVcsOperations,
  ExtensionVcsPatchResult,
  ExtensionVcsRangeEndpoints,
  ExtensionVcsReviewOptions,
  ExtensionVcsShowInput,
  ExtensionVcsSkippedFile,
  ExtensionVcsSkippedFileReason,
  ExtensionVcsStashShowInput,
  ExtensionVcsWatchPlan,
  ExtensionVcsWatchTarget,
  ExtensionVcsWatchTargetSource,
  ExtensionVcsWorkingTreeOperation,
  ExtensionWorkspace,
  ExtensionWorkspaceWriteRequest,
  ExtensionWorkspaceWriteResult,
  HunkExtensionAPI,
  HunkExtensionApiVersion,
  HunkExtensionUserErrorOptions,
  NamedCustomThemeConfig,
  SessionReloadReason,
} from "./types.js";
